import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const yekanFont = localFont({
  src: './yekan.ttf',
});

export const metadata: Metadata = {
  title: 'FE 26',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={yekanFont.className}>{children}</body>
    </html>
  );
}
